name: personal_finance_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  transaction_repository:
    path: packages/transaction_repository
  transaction_api:
    path: packages/transaction_api
  shared_preferences: ^2.0.7
  local_transaction_api:
   path: packages/local_transaction_api
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  pie_chart: ^5.3.2
  firebase_auth: ^3.6.0
  google_sign_in: ^5.4.0
  firebase_core: ^1.20.0
  # flutter_facebook_auth: ^4.4.0+1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  assets:
    - assets/user_page/user.png
  uses-material-design: true
  generate: true
