name: local_transaction_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.7
  rxdart: ^0.27.2
  transaction_api:
    path: ../transaction_api
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
  mocktail: ^0.2.0
