name: transaction_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_serializable: ^6.2.0
  equatable: ^2.0.3
  uuid: ^3.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
